Rescuable721
bgd-labs/solidity-utils pull request #34
Opened 2024-06-28 03:28 UTC by defijesus

2024-06-28 04:13 UTC, sendra commented
Please create the interface and all full natspecs

2024-07-04 03:47 UTC, sendra approved these changes

2024-07-04 22:49 UTC, kyzia551 requested changes

2024-07-04 22:49 UTC, kyzia551 commented on src/contracts/utils/Rescuable721.sol
This contract should either use `Rescuable` as a parent or this logic should be included there. Keeping it as it is right now will not allow usage of both of them at the same time because of clashes

2024-07-04 22:53 UTC, defijesus commented on src/contracts/utils/Rescuable721.sol
sent you a dm on telegram to figure this out

2024-07-07 02:46 UTC, kyzia551 approved these changes

2024-07-08 02:07 UTC, merged